### ISSUE TITLE
https://git.beta.gs/ 使用教程里的脚本地址不对

### ISSUE THREAD

**Issue by z10056** [fcurrk/reinstall#1]
wget --no-check-certificate -O NewReinstall.sh https://git.io/newbetags && chmod a+x NewReinstall.sh && bash NewReinstall.sh

找不到文件，看了一下是GitHub里的文件换了位置

**Comment by fcurrk** [comment]
国内主机无法使用这句，你仔细看看说明

**Comment by z10056** [comment]
> 国内主机无法使用这句，你仔细看看说明

我是国外的鸡，哥，你运行一下那个命令就知道了
https://git.io/newbetags  提示503

**Comment by fcurrk** [comment]
这个是gitgub的短地址，如果不能访问需要自行检查原因，经多人测试还没有人出现这个问题。
可尝试使用https://raw.githubusercontent.com/fcurrk/reinstall/master/NewReinstall.sh

**Comment by z10056** [comment]
> 这个是gitgub的短地址，如果不能访问需要自行检查原因，经多人测试还没有人出现这个问题。 可尝试使用https://raw.githubusercontent.com/fcurrk/reinstall/master/NewReinstall.sh

，在回复完你的当天晚上这个短连接访问不再是503了。现在脚本没啥问题了，可以把这个关了
